### ISSUE TITLE
Afficher le mois courant lors de l'accès au site

### ISSUE THREAD

**Issue by PierreV036** [mlhamel/agendadulibre#27]
Lors de l'accès à la page, l'Agenda du libre du Québec affiche le mois précédant.

**Comment by mlhamel** [comment]
Ca devrait fonctionner maintenant. Si ce n'est pas le pas @PierreV036 fait un "hard refresh" ensuite tout devrait être oki

**Comment by PierreV036** [comment]
C'est fonctionnel.

Merci!
