### ISSUE TITLE
Champ Announced dans le formulaire de soumission

### ISSUE THREAD

**Issue by Peuc** [mlhamel/agendadulibre#35]
Dans le formulaire de soumission d'un nouvel événement, un champ libellé Announced est visible.
Si je comprends bien son intérêt (qui doit être de signaler si un message a fait l'objet d'une annonce ou non), je pense qu'il devrait être réservé aux adminisitrateurs, et caché aux personnes non connectées.
Dans le cas contraire, une description plus précise de son utilité devrait être rajoutée.

**Comment by mlhamel** [comment]
Oui j'ai remarqué que ce champs avait fait sont apparition dans le formulaire, en fait c'est un champs interne qui n'a pas sa raison d'être. Je l'ai déjà caché dans le cadre de le ticket #20 avec ce commit (https://github.com/mlhamel/agendadulibre/commit/b464bc91749ab8d63eb5c983f5d63a2dbf7884a3)
